trigger:
  - master 

pr:
  autoCancel: true
  branches:
    include:
      - master

schedules:
- cron: "0 0 * * *"
  displayName: Daily midnight build for master
  branches:
    include:
    - master
  always: true

jobs:
  - job: TestsForGMSO
    strategy:
      matrix:
        Python36Ubuntu:
          imageName: 'ubuntu-latest'
          python.version: 3.6
        Python37Ubuntu:
          imageName: 'ubuntu-latest'
          python.version: 3.7
        Python38Ubuntu:
          imageName: 'ubuntu-latest'
          python.version: 3.8
        Python36macOS:
          imageName: 'macOS-latest'
          python.version: 3.6
        Python37macOS:
          imageName: 'macOS-latest'
          python.version: 3.7
        Python38macOS:
          imageName: 'macOS-latest'
          python.version: 3.8

    pool:
      vmImage: $(imageName)

    steps:
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to path

      - bash: sudo chown -R $USER $CONDA
        condition: eq( variables['Agent.OS'], 'Darwin' )
        displayName: Take ownership of conda installation

      - bash: |
          conda config --set always_yes yes --set changeps1 no
          conda config --add channels omnia
          conda config --add channels janschulz
          conda config --add channels conda-forge
          conda config --add channels mosdef
        displayName: Add relavent channels

      - bash: |
          conda create -n test-environment
          source activate test-environment
          conda install --yes --file requirements-test.txt
          conda install pytest
          pip install -e .
        displayName: Install requirements, Install branch

      - bash: |
          source activate test-environment
          python -m pytest -v gmso/tests/ 
          python -m pytest -v --cov=gmso --cov-report=html --pyargs gmso
        displayName: Run Tests

      - bash: |
          source activate test-environment
          coverage xml
          codecov --file ./coverage.xml --token 4020cb2c-5787-485a-92f2-5d106dff85a1
          coverage html
        condition: and( eq( variables['Agent.OS'], 'Linux' ), eq( variables['python.version'], '3.7' ) )
        displayName: Upload Coverage Report
      
      - task: PublishCodeCoverageResults@1
        inputs: 
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
          reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
        condition: and( eq( variables['Agent.OS'], 'Linux' ), eq( variables['python.version'], '3.7' ) )
        displayName: Publish Coverage Report
